name: SimpleMessage
version: 1.1
main: de.zagro.simplemessage.Main
author: Zagro

commands:
  message:
    aliases:
      - msg
  reply:
    aliases:
      - r

permissions:
  simplemessage.*:
    description: Allows you to have all permissions from this plugin
  simplemessage.message:
    description: Allows you to use the /msg command
  simplemessage.reply:
    description: Allsows you to use the /r command
