name: SimpleMessage
version: ${project.version}
main: de.zagro.simplemessage.Main
authors: [ Zagro ]

commands:
  message:
    aliases:
      - msg
  reply:
    aliases:
      - r

permissions:
  simplemessage.*:
  simplemessage.message:
  simplemessage.reply:
